razum2um/awesome-clojure

README.md

Add two interesting websites.
4clojure contains more than 150 interactive problems to solve in Clojure.
Try Clojure provides an online REPL with a interactive guide through the REPL.

Add 4clojure and Try Clojure under the Websites category.

---

README.md

Fixed invalid link to Prismatic's schema repo

Fixed Prismatic's schema link

---

README.md

Alda is a DSL for audio production

Inclusion of alda

---

README.md

http://www.clojuresphere.com/ doesn't seem to be working anymore.

remove ClojureSphere

---

README.md

Create regexes without any regex

Verbal Exprejon

---

README.md

update table of content, And also add ci in.

[lambeta] update index and add ci in

---

README.md

- klipse is an advanced library to do online code evaluation using bootstrapped clojurescript
- milestones (my library) is a lib to schedule project tasks execution given a work breakdown structure.

Add milestones and klipse

---

README.md

flambo: spark dsl
sparkling: spark dsl
cortex: clojure machine learning

spark dsl and machine learning library

---

README.md

I have added Liquid - a text editor written in pure Clojure - to the list.

Added Liquid to the list.

---

README.md

Add Compojure reference

---

README.md

Redis client for Clojure wrapping Lettuce (Redis client for Java based on Netty)

Add redis client celtuce

---

README.md

Codewars has got 300 Katas (and growing) in Clojure

Add Codewars to Exercises

---

README.md

It can be a great help for beginners. Feel free to refile it if need be.

Add error message catalog

---

README.md

From:
http://jayfields.com/expectations/
To:
https://github.com/clojure-expectations/expectations

fix broken link Expectations

---

README.md

Someone commented on https://www.reddit.com/r/Clojure/comments/99nhw5/why_doesnt_rich_hickey_or_a_few_clojure_experts/e4so6hb that some links to video tutorials on Clojure could be added to this repo, so here's a PR :wink:

Added a Video tutorials section

---

README.md

* update elasticsearch libs with correct name
* add spandex (more recent/up-to-date elastic-search lib)
* add qbits.ex on exceptions handling

* add cassandra client library

---

README.md

[Calva](https://github.com/BetterThanTomorrow/calva) - Calva: Clojure & ClojureScript support for VS Code.
Integrated REPL, linting, inline eval, test runner, and more. Powered by Cider & nRepl.

Added Calva to editor plugins

---

README.md

Adding GraphQL section with Lacinia as a first library

Adding GraphQL section

---

README.md

[vim-iced](https://github.com/liquidz/vim-iced): Clojure Interactive Development Environment for Vim8/Neovim.

Added vim-iced to editor plugins

---

README.md

Nice and popular graph library for Clojure.

Add Loom (graph lib)

---

README.md

Two Vim plugins that are both pretty mature - vim-cljfmt and vim-eastwood.

Add more Vim plugins

---

README.md

Added section for forward-chaining rule engines.

add rule-based programming section

---

README.md

One of my favourite linters. Very minimal.

Add clj-kondo

---

README.md

https://github.com/lambdaisland/trikl

Adding trikl

---

README.md

The app has heavy JS based front-end, all of the text generation backend and APIs are implemented in Clojure

doc: add natural language generation app

---

README.md

Owner took it down.
See https://twitter.com/arrdem/status/1144065851370299392

Removed Grimoire.

---

README.md

https://github.com/funcool/struct

Add struct library to "Data Validation" group

---

README.md

Datalevin is a durable datalog database.

add Datalevin

---

README.md

The [`secrets`](https://github.com/lk-geimfari/secrets.clj) is a library designed to generate cryptographically strong random numbers suitable for managing data such as passwords, account authentication, security tokens, and related secrets.
The [`secrets`](https://github.com/lk-geimfari/secrets.clj) is an implementation of the [`secrets`](https://docs.python.org/3/library/secrets.html) module from Python's standard library for Clojure.
See [«Recipes and best practices»](#recipes-and-best-practices) for usage examples.

Add secrets.clj

---

README.md

Hey @razum2um 
just fixing a link here...
Cheers!

Fixing link for "mal"

---

README.md

Hey @razum2um 
just fixing a link - GitHub repo doesn't exist (anymore).
Cheers!

Fixing dead link

---

README.md

Add clojureVSCode editor plugin

---

README.md

Looks like a typo @razum2um...

tranducers -> transducers

---

README.md

https://clojure-lsp.github.io/clojure-lsp/

Add clojure-lsp

---

README.md

I'm a long-term Clojure + Vim user and I've used all the plugins. Conjure definitely deserves hall-of-fame status. Thanks for a great (awesome!) list.

Add Conjure to Editor Plugins section of README

---

README.md

Blog, discussion, etc. are dead now, sadly

archiving Lighttable

---

README.md

Hello,
I noticed that the testing framework, StateFlow wasn't in the list, so I added it.

Add StateFlow

---

README.md

add tools.build to build-automation-and-package-management

add tools.build

---

README.md

Rules engine I find more compelling than either Clara or Arete.
Added in inverse alphabetical order for that section since I had 3 possibilities so chose one of them.

Add the O'doyle rules engine

---

README.md

I've recently released a new library that fills the same space as Kibit called [Splint](https://github.com/NoahTheDuke/splint).

Add splint to Code Analysis section

---

README.md

Proposing to add column - https://gitlab.com/demonshreder/column - a batteries included template for Pedestal framework.

Add column to Web Framework

---

README.md

https://github.com/gigasquid/wonderland-clojure-katas

Add Wonderland Clojure Katas

---

README.md

http://clojurekatas.org link is broken

Remove Clojure Katas from Exercises
